//client
#include <stdio.h>
#include <rpc/rpc.h> /* standard RPC include file */
#include "file.h"
/* this file is generated by rpcgen */
main(int argc, char *argv[])
{
  CLIENT *cl;
  /* RPC handle */
  char *server,*path;
  char **sresult; /* return value from get_date_1() */
  if (argc != 3)
  {
          fprintf(stderr, "usage: %s <hostname> <filename>\n", argv[0]);
          exit(1);
  }
  server = argv[1];
  path=argv[2];
  /*
   * * Create client handle
   * */
  if ((cl = clnt_create(server, FILE_PROG, FILE_VERS, "udp")) == NULL)
  {
  /*
   * * can't establish connection with server
   * */
          clnt_pcreateerror(server);
          exit(2);
  }
  /*
   * * Now call the remote procedure get_date
   * */
  if ( (sresult = get_file_1(&path,cl)) == NULL)
  {
          clnt_perror(cl, server);
          exit(4);
  }
  printf("\nFile from host %s is =\n%s\n", server, *sresult);
  clnt_destroy(cl);
  /* done with the handle */
  exit(0);
}
